name: project_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  pinput: ^5.0.0
  sizer: ^2.0.15
  syncfusion_flutter_sliders: ^26.2.14
  input_slider: ^0.3.1
  dot_curved_bottom_nav: ^0.0.2
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  dio: ^5.7.0
  animated_bottom_navigation_bar: ^1.3.3
  device_preview: ^1.2.0
  dotted_border: ^2.1.0
  outlined_text: ^1.0.1
  percent_indicator: ^4.2.3
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/